sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install: pip install tox-travis python-coveralls codecov
script: tox -- --cov paymaster --cov-report term-missing
after_success:
  - coveralls
  - codecov